version: '3.9'

services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"

    depends_on:
      - backend

  backend:
    build: ./backend

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - appnet

  db:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - appnet

networks:
  appnet:

volumes:
  mysql_data:
